
    create table article_favorites (
        article_id bigint not null,
        user_id bigint not null,
        primary key (article_id, user_id)
    );

    create table article_tags (
        article_id bigint not null,
        tag_id bigint not null,
        primary key (article_id, tag_id)
    );

    create table articles (
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        body varchar(255) not null,
        description varchar(255) not null,
        slug varchar(255) unique,
        title varchar(255) not null,
        primary key (id)
    );

    create table comments (
        article_id bigint not null,
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        body varchar(255) not null,
        primary key (id)
    );

    create table tags (
        id bigint generated by default as identity,
        tag_name varchar(255) not null unique,
        primary key (id)
    );

    create table user_follows (
        followed_id bigint not null,
        follower_id bigint not null,
        primary key (followed_id, follower_id)
    );

    create table users (
        id bigint generated by default as identity,
        bio varchar(255),
        email varchar(255) not null unique,
        image varchar(255),
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    create index idx_article_slug 
       on articles (slug);

    create index idx_user_email 
       on users (email);

    create index idx_user_username 
       on users (username);

    alter table if exists article_favorites 
       add constraint fk_user_favorites 
       foreign key (user_id) 
       references users;

    alter table if exists article_favorites 
       add constraint fk_article_favorites 
       foreign key (article_id) 
       references articles 
       on delete cascade;

    alter table if exists article_tags 
       add constraint fk_tag_articles 
       foreign key (tag_id) 
       references tags;

    alter table if exists article_tags 
       add constraint fk_article_tags 
       foreign key (article_id) 
       references articles;

    alter table if exists articles 
       add constraint fk_article_author 
       foreign key (author_id) 
       references users;

    alter table if exists comments 
       add constraint fk_comment_article 
       foreign key (article_id) 
       references articles;

    alter table if exists comments 
       add constraint fk_comment_author 
       foreign key (author_id) 
       references users;

    alter table if exists user_follows 
       add constraint fk_user_followed 
       foreign key (followed_id) 
       references users;

    alter table if exists user_follows 
       add constraint fk_user_follower 
       foreign key (follower_id) 
       references users;
